### PR TITLE
Change pr_url parameter search on cancel builds in case the parameter is repeated

### PR DESCRIPTION
**Pull request by jorgeelas**
@HectorGarciaAlvarez @gsanchezu This is only a guess but i think the order of the parameters could be messing with the cancel build

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/449/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/450/ for more details.

**Comment by jorgeelas** [comment]
@gsanchezu The version of the library we have does not have this method implemented. I think it is very risky to update that because this small change. Currently the pr is not closing old pr with the same origin, my guess is that the order of the parameter is important with the current implementation

**Comment by jorgeelas** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/451/ for more details.

**Comment by HectorGarciaAlvarez** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.135 and Jenkins instance at https://10.166.246.136

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/453/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.135 and Jenkins instance at https://10.166.246.136

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/454/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-anozcz, https://ops.elasticbox.com/services/instances/i-qked06

**Pull request merged**
