### PR TITLE
Add wait for availability in Stop operation

### PR DESCRIPTION
**Pull request by gsanchezu**
@GustavoLlorente, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/447/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/448/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/449/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 2

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/450/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 3

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/451/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, again 4

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.44 and Jenkins instance at https://10.166.246.34

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/452/ for more details.

**Comment by GustavoLlorente** [comment]
It's OK form me! ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-4khdhb, https://ops.elasticbox.com/services/instances/i-svrnd9, https://ops.elasticbox.com/services/instances/i-70citw

**Pull request merged**
