### PR TITLE
[EBE-4964] Fix job 'ebx_jenkins_plugin_test_indigo' by refreshing Appliance settings

### PR DESCRIPTION
**Pull request by gsanchezu**
There is an upgrade&restart of the appliance already, so I opt to update the IP before this part for the changes to take effect with a single restart.

@EfrenRey, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/458/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please again

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.51 and Jenkins instance at https://10.166.246.18

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/459/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-apsf9c, https://ops.elasticbox.com/services/instances/i-me7u08

**Pull request merged**
