### PR TITLE
Add Animal Sniffer Maven plugin signature

### PR DESCRIPTION
**Pull request by gsanchezu**
CloudBees Jenkins PR test was failing because this plugin configuration was not present in our pom.

@DiegoSanjuan, 👍 ?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.53.47 and Jenkins instance at https://10.0.48.182

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/427/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.226 and Jenkins instance at https://10.0.48.227

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/428/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/429/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/430/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/431/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.226 and Jenkins instance at https://10.0.48.227

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/432/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-x5albo, https://ops.elasticbox.com/services/instances/i-dmu34c

**Pull request merged**
