### PR TITLE
Add EBX Appliance IP update for tests

### PR DESCRIPTION
**Pull request by gsanchezu**
@jhita, @jorgeelas please review, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/433/ for more details.

**Comment by jhita** [comment]
ACK!

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/434/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.140.45.44 and Jenkins instance at https://10.140.45.19

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/436/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-oi41jo, https://ops.elasticbox.com/services/instances/i-8f1sxd

**Pull request merged**
