### PR TITLE
[CAM-7458] Add support in CAM Jenkins plugin for newer versions of Je…

### PR DESCRIPTION
**Pull request by julio-castanar**
@gsanchezu 
Could you review this pull request, please?
@HectorGarciaAlvarez
Please, could you try the elasticbox.hpi plugin in artifacts results from this PR?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.52 and Jenkins instance at https://10.166.246.68

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/524/ for more details.

**Comment by julio-castanar** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.52 and Jenkins instance at https://10.166.246.73

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/525/ for more details.

**Comment by julio-castanar** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.52 and Jenkins instance at https://10.166.246.36

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/526/ for more details.

**Comment by julio-castanar** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.52 and Jenkins instance at https://10.166.246.54

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/527/ for more details.

**Comment by julio-castanar** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.166.246.52 and Jenkins instance at https://10.166.246.51

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/528/ for more details.

**Comment by julio-castanar** [comment]
Please, review and merge this PR

**Comment by allyourbotsarebelongtous** [comment]
Instance i-dhf46o couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
Instance i-kuc4c4 couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
Instance i-nwmutb couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
Instance i-1skxxv couldnt be deleted. It requires manual deletion

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-dhf46o, https://ops.elasticbox.com/services/instances/i-kuc4c4, https://ops.elasticbox.com/services/instances/i-wkzxa3, https://ops.elasticbox.com/services/instances/i-nwmutb, https://ops.elasticbox.com/services/instances/i-vj2w4x, https://ops.elasticbox.com/services/instances/i-1skxxv

**Pull request merged**
