### PR TITLE
Update github-api and jackson

### PR DESCRIPTION
**Pull request by bitwiseman**
Use the latest github-api.  This new version doesn't bundle jackson, instead depending on the jackson2-api-plugin.

https://github.com/jenkinsci/github-api-plugin/blob/960741d4248b6994654837f3c0d45a1a00f81b1a/pom.xml#L34-L38

@afavieres @gsanchezu

### CODE REVIEW

**Comment by afavieres** [comment]
I think that I no longer do reviews of this. However, it looks good. I suppose that the jackson version of the plugin has the same major number than the old pom, right?

**Comment by bitwiseman** [comment]
@afavieres 
Yes, jackson is still 2.x.

**Comment by bitwiseman** [comment]
@afavieres @gsanchezu  
Doh, sorry, there are (of course) some enforcer violations.

**Comment by bitwiseman** [comment]
Some test failures remain: 

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] com.elasticbox.jenkins.SlaveProvisionTest.testSlaveProvision
[ERROR]   Run 1: SlaveProvisionTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.SlaveProvisionTest.testSlaveProvisionFailingAttempts
[ERROR]   Run 1: SlaveProvisionTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.BindingWithTagsTest.testBindingWithTags
[ERROR]   Run 1: BindingWithTagsTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: BindingWithTagsTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.BuildStepTest.testBuildWithSteps
[ERROR]   Run 1: BuildStepTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: BuildStepTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client Inv...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.CompatibilityTest.testBuildWithOldSteps
[ERROR]   Run 1: CompatibilityTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: CompatibilityTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.ElasticBoxCloudTest.testClient
[ERROR]   Run 1: ElasticBoxCloudTest.setupTestData:43 » Client Invalid Token
[ERROR]   Run 2: ElasticBoxCloudTest.cleanUp:50 » Client Invalid Token
[ERROR]   Run 3: ElasticBoxCloudTest>TestBase.tearDown:70 » Client Invalid Token
[INFO]
[ERROR] com.elasticbox.jenkins.tests.InjectEnvVariablesTest.testInstanceEnvVariables
[ERROR]   Run 1: InjectEnvVariablesTest.setupTestData:39 » Client Invalid Token
[ERROR]   Run 2: InjectEnvVariablesTest>TestBase.tearDown:70 » Client Invalid Token
[INFO]
[ERROR] com.elasticbox.jenkins.tests.InstanceExpirationTest.testInstanceExpiration
[ERROR]   Run 1: InstanceExpirationTest.setupTestData:31->ComputeServiceTestBase.setupTestData:39 » Client
[ERROR]   Run 2: InstanceExpirationTest>TestBase.tearDown:70 » Client Invalid Token
[INFO]
[ERROR] com.elasticbox.jenkins.tests.ManageInstanceTest.testManageInstance
[ERROR]   Run 1: ManageInstanceTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: ManageInstanceTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.PullRequestLifecycleManagementTest.testPullRequestLifecycleManagement
[ERROR]   Run 1: PullRequestLifecycleManagementTest>PullRequestTestBase.setup:104->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: PullRequestLifecycleManagementTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.PullRequestManagerTest.testPullRequestsForMultipleProjects
[ERROR]   Run 1: PullRequestManagerTest.setup:54->PullRequestTestBase.setup:104->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: PullRequestManagerTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.SelectPolicyByClaimsTests.testDeployWithPolicyByClaims
[ERROR]   Run 1: SelectPolicyByClaimsTests>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: SelectPolicyByClaimsTests>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.SlaveProvisionWithPolicyByClaimsTest.testSlaveProvision
[ERROR]   Run 1: SlaveProvisionWithPolicyByClaimsTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionWithPolicyByClaimsTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[ERROR] com.elasticbox.jenkins.tests.UpdateBoxTest.testUpdateBox
[ERROR]   Run 1: UpdateBoxTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: UpdateBoxTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client Inv...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.UpdateInstanceTest.testUpdateInstance
[ERROR]   Run 1: UpdateInstanceTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: UpdateInstanceTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
[INFO]
[INFO]
[ERROR] Tests run: 71, Failures: 0, Errors: 15, Skipped: 0
```

**Comment by bitwiseman** [comment]
Looks like these same errors occur on the `master` branch for me.  Only difference is the retries are in the 50+ range instead of just 2. 

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR] com.elasticbox.jenkins.SlaveProvisionTest.testSlaveProvision(com.elasticbox.jenkins.SlaveProvisionTest)
[ERROR]   Run 1: SlaveProvisionTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.SlaveProvisionTest.testSlaveProvisionFailingAttempts(com.elasticbox.jenkins.SlaveProvisionTest)
[ERROR]   Run 1: SlaveProvisionTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.BindingWithTagsTest.testBindingWithTags(com.elasticbox.jenkins.tests.BindingWithTagsTest)
[ERROR]   Run 1: BindingWithTagsTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: BindingWithTagsTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.BuildStepTest.testBuildWithSteps(com.elasticbox.jenkins.tests.BuildStepTest)
[ERROR]   Run 1: BuildStepTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: BuildStepTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client Inv...
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.CompatibilityTest.testBuildWithOldSteps(com.elasticbox.jenkins.tests.CompatibilityTest)
[ERROR]   Run 1: CompatibilityTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: CompatibilityTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.ElasticBoxCloudTest.testClient(com.elasticbox.jenkins.tests.ElasticBoxCloudTest)
[ERROR]   Run 1: ElasticBoxCloudTest.setupTestData:43 » Client Invalid Token
[ERROR]   Run 2: ElasticBoxCloudTest.cleanUp:50 » Client Invalid Token
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.InjectEnvVariablesTest.testInstanceEnvVariables(com.elasticbox.jenkins.tests.InjectEnvVariablesTest)
[ERROR]   Run 1: InjectEnvVariablesTest.setupTestData:39 » Client Invalid Token
[ERROR]   Run 2: InjectEnvVariablesTest>TestBase.tearDown:70 » Client Invalid Token
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.InstanceExpirationTest.testInstanceExpiration(com.elasticbox.jenkins.tests.InstanceExpirationTest)
[ERROR]   Run 1: InstanceExpirationTest.setupTestData:31->ComputeServiceTestBase.setupTestData:39 » Client
[ERROR]   Run 2: InstanceExpirationTest>TestBase.tearDown:70 » Client Invalid Token
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.ManageInstanceTest.testManageInstance(com.elasticbox.jenkins.tests.ManageInstanceTest)
[ERROR]   Run 1: ManageInstanceTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: ManageInstanceTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.PullRequestLifecycleManagementTest.testPullRequestLifecycleManagement(com.elasticbox.jenkins.tests.PullRequestLifecycleManagementTest)
[ERROR]   Run 1: PullRequestLifecycleManagementTest>PullRequestTestBase.setup:104->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: PullRequestLifecycleManagementTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.PullRequestManagerTest.testPullRequestsForMultipleProjects(com.elasticbox.jenkins.tests.PullRequestManagerTest)
[ERROR]   Run 1: PullRequestManagerTest.setup:54->PullRequestTestBase.setup:104->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: PullRequestManagerTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.SelectPolicyByClaimsTests.testDeployWithPolicyByClaims(com.elasticbox.jenkins.tests.SelectPolicyByClaimsTests)
[ERROR]   Run 1: SelectPolicyByClaimsTests>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: SelectPolicyByClaimsTests>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.SlaveProvisionWithPolicyByClaimsTest.testSlaveProvision(com.elasticbox.jenkins.tests.SlaveProvisionWithPolicyByClaimsTest)
[ERROR]   Run 1: SlaveProvisionWithPolicyByClaimsTest>SlaveProvisionTestBase.setup:56->BuildStepTestBase.setup:47 » Client
[ERROR]   Run 2: SlaveProvisionWithPolicyByClaimsTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.UpdateBoxTest.testUpdateBox(com.elasticbox.jenkins.tests.UpdateBoxTest)
[ERROR]   Run 1: UpdateBoxTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: UpdateBoxTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client Inv...
...
[INFO]
[ERROR] com.elasticbox.jenkins.tests.UpdateInstanceTest.testUpdateInstance(com.elasticbox.jenkins.tests.UpdateInstanceTest)
[ERROR]   Run 1: UpdateInstanceTest>BuildStepTestBase.setup:47 » Client Invalid Token
[ERROR]   Run 2: UpdateInstanceTest>BuildStepTestBase.tearDown:88->TestBase.tearDown:70 » Client
...
[INFO]
[INFO]
[ERROR] Tests run: 71, Failures: 0, Errors: 15, Skipped: 0
```

**Pull request closed without merging**
