### PR TITLE
Fix tests warnings and 1 deploy failure

### PR DESCRIPTION
**Pull request by gsanchezu**
@DiegoSanjuan, 👍?

### CODE REVIEW

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.146 and Jenkins instance at https://10.0.48.147

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/424/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.146 and Jenkins instance at https://10.0.48.147

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/425/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.146 and Jenkins instance at https://10.0.48.147

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/426/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-46zz18, https://ops.elasticbox.com/services/instances/i-wzpxgn

**Pull request merged**
