### PR TITLE
Fixes/ebe4207 plugin test indigo

### PR DESCRIPTION
**Pull request by gsanchezu**
@jhita, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.140.45.43 and Jenkins instance at https://10.140.45.42

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/437/ for more details.

**Comment by jhita** [comment]
OK!

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-e7s9l7, https://ops.elasticbox.com/services/instances/i-0phje2

**Pull request merged**
