### PR TITLE
Fixes for job Jenkins plugin test indigo

### PR DESCRIPTION
**Pull request by gsanchezu**
@EfrenRey, @GustavoLlorente, could you please take a look and review? Thanks!

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/438/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.140.45.70 and Jenkins instance at https://10.140.45.43

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/440/ for more details.

**Comment by GustavoLlorente** [comment]
OK!

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-muj1yq, https://ops.elasticbox.com/services/instances/i-fpor25

**Pull request merged**
