### PR TITLE
[EBE-3543] Update github plugin version

### PR DESCRIPTION
**Pull request by gsanchezu**
Update github and github-api plugins to latest version
Fix code to support the update

@osanjuan, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.53.47 and Jenkins instance at https://10.0.48.36

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/421/ for more details.

**Comment by gsanchezu** [comment]
Added fix for instanceName required for App boxes.
@osanjuan, 👍?

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/422/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-fihnai, https://ops.elasticbox.com/services/instances/i-qq5kdh

**Pull request merged**
